# POST http://localhost:5000/produk 
# Content-Type: application/json

# {
#     "namaproduk" : "roti kukus",
#     "deskripsi" :"roti kering",
#     "kategori" : "roti kering",
#     "jumlah" : 20,
#     "harga" : 2000,
#     "discount" : 10
# }

# POST http://localhost:5000/user 
# Content-Type: application/json

# {
#     "nama": "martin",
#     "email": "martin@gmail.com",
#     "status": "client",
#     "alamat": "payaman",
#     "notlpn": "08951271261",
#     "password": "wer1234ui"
# }

POST http://localhost:5000/pesanan
Content-Type: application/json

{
    "idpemesan": "65d62a0bf4887c71539eee90",
    "namapemesan": "martin",
    "items": [
        {
            "produk_id": "65db674b4897250bac800724",
            "namaproduk": "roti salju",
            "harga": 5000,
            "jumlah": 2
        },
        {
            
            "produk_id": "65db67854897250bac800726",
            "namaproduk": "roti kukus",
            "harga": 5000,
            "jumlah": 2
        }
    ],
    "alamat": "madiun",
    "notlpn": "0891723712912",
    "total": 10000,
    "statusbayar": "pending",
    "statusditerima": "belum diterima",
    "tglorder": "04-02-2024"

}