export { default as Dashboard } from "./Dashboard";
export { default as Products } from "./Products";
export { default as AddProduct } from "./AddProduct";
export { default as SingleProduct } from "./SingleProduct";
export { default as Customers } from "./Customers";
export { default as SingleCustomer } from "./SingleCustomer";
export { default as SalesAnalytics } from "./SalesAnalytics";
export { default as ProductSales } from "./ProductSales";
export { default as Orders } from "./Orders";
export { default as SingleOrder } from "./SingleOrder";
export { default as Transactions } from "./Transactions";
export { default as Settings } from "./Settings";
export { default as Login } from "./login";
export { default as UserProfil } from "./userProfil";
export { default as Popup } from "./PopUp";
export { default as Edit } from "./edit"
